receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Group spans by trace for proper field summing across spans
  groupbytrace:
    wait_duration: 10s
    num_traces: 100

  # Transform processor to add field summing - simplified for testing
  transform:
    trace_statements:
      - context: span
        statements:
          # Add marker attribute to getData spans for now
          - set(attributes["field_summing_enabled"], true) where name == "compute.v1.ComputeEngine/getData"

  # Batch processor for performance
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  # Export traces with summed fields to Honeycomb
  otlp/honeycomb:
    endpoint: "https://api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "field-summing-traces"
      
  # Debug logging
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [groupbytrace, transform, batch]
      exporters: [otlp/honeycomb, debug]