apiVersion: batch/v1
kind: Job
metadata:
  name: field-summing-collector-job
  namespace: observability
spec:
  template:
    spec:
      containers:
      - name: trace-generator
        image: field-summing-collector:latest
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycomb-secret
              key: api-key
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /root/job-config.yaml
          subPath: job-config.yaml
      volumes:
      - name: config
        configMap:
          name: trace-generator-config
      restartPolicy: OnFailure
  backoffLimit: 3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trace-generator-config
  namespace: observability
data:
  job-config.yaml: |
    trace_generator:
      collector_endpoint: "http://otel-collector:4318"
      traces_per_batch: 10
      batch_interval: "60s"
      total_batches: 5
      services:
        - name: "appserver"
          enabled: true
        - name: "compute" 
          enabled: true
        - name: "datasource-proxy"
          enabled: true
        - name: "series-cache"
          enabled: true
    logging:
      level: "info"
      format: "json"

---
apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-secret
  namespace: observability
type: Opaque
data:
  api-key: # base64 encoded Honeycomb API key

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: field-summing-collector-cronjob
  namespace: observability
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: trace-generator
            image: field-summing-collector:latest
            env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4318"
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-secret
                  key: api-key
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
          restartPolicy: OnFailure